-- 코드를 입력하세요
SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FAVORITES
FROM 
(
    SELECT FOOD_TYPE, max(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) T, 
REST_INFO
WHERE REST_INFO.FOOD_TYPE = T.FOOD_TYPE AND REST_INFO.FAVORITES = T.FAVORITES 
ORDER BY REST_INFO.FOOD_TYPE DESC

