-- 코드를 입력하세요
SELECT 
TO_NUMBER(TO_CHAR(T1.START_DATE,'mm')) AS MONTH, 
T1.CAR_ID, 
COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T1, 
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE,'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) T2
WHERE T1.CAR_ID = T2.CAR_ID
AND TO_CHAR(T1.START_DATE,'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP BY TO_NUMBER(TO_CHAR(T1.START_DATE,'mm')), T1.CAR_ID
ORDER BY MONTH,CAR_ID DESC