-- 코드를 입력하세요
SELECT '/home/grep/src/' || T.BOARD_ID || '/' || T.FILE_ID || T.FILE_NAME || T.FILE_EXT AS FILE_PATH
FROM USED_GOODS_FILE T
WHERE BOARD_ID =(SELECT BOARD_ID
FROM USED_GOODS_BOARD
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD))
ORDER BY T.FILE_ID DESC