-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, U.CITY || ' ' ||
CONCAT(U.STREET_ADDRESS1,CONCAT(' ', U.STREET_ADDRESS2)) AS 전체주소,
SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4) AS 전화번호
FROM USED_GOODS_USER U, 
(
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(*) > 2
) B
WHERE U.USER_ID = B.WRITER_ID
ORDER BY U.USER_ID DESC