-- 코드를 입력하세요
SELECT T.NAME, T.datetime
FROM (SELECT I.NAME, I.datetime
FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.datetime) T
WHERE ROWNUM <= 3
