-- -- 코드를 입력하세요
WITH MEMBER_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        )
    )
)

SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE PF JOIN REST_REVIEW RV ON PF.member_id = RV.member_id
WHERE PF.MEMBER_ID IN (SELECT MEMBER_ID FROM MEMBER_COUNT)
ORDER BY REVIEW_DATE, REVIEW_TEXT
;

