-- 코드를 입력하세요
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_CAR C
WHERE H.CAR_ID = C.CAR_ID
AND C.CAR_TYPE = '세단'
AND TO_CHAR(H.START_DATE, 'YYYY-MM') = '2022-10'
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC